### ISSUE TITLE
Github actions failing

### ISSUE THREAD

**Issue by Panosfunk** [cph-cachet/carp_studies_app#396]
Flutter stable branch is now not so stable. Therefore our github actions that were cloning flutter -b stable broke. This is fixed like so in build.yml action:
Instead of 
```
git clone https://github.com/flutter/flutter.git --depth 1 -b stable $HOME/flutter
```
I now use: 
```
 - name: Setup Flutter SDK
    uses: flutter-actions/setup-flutter@v4
    with:
        channel: stable
        version: 3.29.0
```
and for ci_post_clone.sh:
Instead of just 
```
git clone https://github.com/flutter/flutter.git --depth 1 -b stable $HOME/flutter
```
I now do 

```
git clone https://github.com/flutter/flutter.git --depth 1 -b 3.24.5 $HOME/flutter
```
